# DataSource Config

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mb_plus?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto                              # 全局主键自增策略,auto为自动增长
      logic-delete-value: -1                     #逻辑删除字段值, 配合注解使用 -1 为删除状态
      logic-not-delete-value: 0                  #逻辑删除字段值, 配合注解使用 0 为正常状态
    refresh: true






# Logger Config
logging:
  level:
    com.canxue.mbtest: debug
    java.sql: debug
    org.apache.ibatis: info
